import {
  AirVent,
  Snowflake,
  Fan,
  Wind,
  Waves,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Gauge,
  Settings,
  Settings2,
  SlidersHorizontal,
  SlidersVertical,
  Power,
  Timer,
  Clock,
  CircleGauge,
  CloudSnow,
  CloudSun,
  Sun,
  PlugZap,
  Plug,
  Plug2,
  Unplug,
  Zap,
  ZapOff,
  Cable,
  CableCar,
  Lightbulb,
  LightbulbOff,
  Lamp,
  LampDesk,
  LampCeiling,
  LampFloor,
  LampWallDown,
  LampWallUp,
  Battery,
  BatteryCharging,
  BatteryFull,
  UtilityPole,
  Droplets,
  Droplet,
  DropletOff,
  ShowerHead,
  Bath,
  Toilet,
  Wrench,
  Pipette,
  GlassWater,
  WavesLadder,
  LifeBuoy,
  Container,
  Cylinder,
  CircleDashed,
  CircleDot,
  CircleOff,
  RefreshCw,
  ArrowDownToLine,
  ArrowUpFromLine,
  Filter,
  Hammer,
  Drill,
  Grip,
  Pickaxe,
  Axe,
  Ruler,
  RulerDimensionLine,
  TriangleRight,
  HardHat,
  Construction,
  BrickWall,
  Paintbrush,
  PaintRoller,
  PaintBucket,
  Brush,
  Anvil,
  Nut,
  Bolt,
  PocketKnife,
  ToolCase,
  Sparkles,
  SprayCan,
  Bubbles,
  SoapDispenserDroplet,
  WashingMachine,
  Shirt,
  TowelRack,
  Hand,
  Trash,
  Trash2,
  Recycle,
  Eraser,
  PaintbrushVertical,
  BrushCleaning,
  SquareStack,
  HandMetal,
  Scissors,
  FoldHorizontal,
  FoldVertical,
  RectangleHorizontal,
  CookingPot,
  ChefHat,
  Utensils,
  UtensilsCrossed,
  Microwave,
  Refrigerator,
  Heater,
  Coffee,
  CupSoda,
  Wine,
  BottleWine,
  Soup,
  Sandwich,
  EggFried,
  Beef,
  Fish,
  Salad,
  Apple,
  Pizza,
  Cake,
  House,
  HousePlus,
  HouseHeart,
  HousePlug,
  HouseWifi,
  Building,
  Building2,
  Hotel,
  Sofa,
  Armchair,
  Bed,
  BedDouble,
  BedSingle,
  DoorOpen,
  DoorClosed,
  PanelsTopLeft,
  Fence,
  Blinds,
  Wallpaper,
  Grid2X2,
  Leaf,
  LeafyGreen,
  Flower,
  Flower2,
  Sprout,
  TreePine,
  Trees,
  TreeDeciduous,
  Shrub,
  Shovel,
  Snail,
  Bug,
  BugOff,
  Rat,
  Bird,
  CloudRain,
  SunMedium,
  Sunrise,
  Tent,
  Mountain,
  Baby,
  PersonStanding,
  Accessibility,
  Heart,
  HeartPulse,
  Stethoscope,
  Cross,
  Bandage,
  Pill,
  Syringe,
  Activity,
  HandHeart,
  HandHelping,
  Dog,
  Cat,
  PawPrint,
  Rabbit,
  Turtle,
  Bone,
  Footprints,
  Truck,
  TruckElectric,
  Car,
  CarFront,
  CarTaxiFront,
  Bike,
  Motorbike,
  Bus,
  Van,
  Package,
  PackageOpen,
  PackageCheck,
  PackagePlus,
  Boxes,
  Box,
  Archive,
  Warehouse,
  Forklift,
  Luggage,
  BaggageClaim,
  Shield,
  ShieldCheck,
  ShieldAlert,
  ShieldPlus,
  ShieldHalf,
  Lock,
  LockOpen,
  Key,
  KeyRound,
  KeySquare,
  Cctv,
  Camera,
  Video,
  BellElectric,
  BellRing,
  Siren,
  FireExtinguisher,
  Flame,
  AlarmSmoke,
  Fingerprint,
  Tv,
  TvMinimal,
  Monitor,
  MonitorCog,
  Laptop,
  Computer,
  Smartphone,
  Tablet,
  Printer,
  Router,
  Wifi,
  EthernetPort,
  Speaker,
  Headphones,
  Radio,
  Gamepad2,
  Projector,
  Usb,
  CircuitBoard,
  Cpu,
  type LucideIcon,
} from 'lucide-react';

export interface CategoryIconOption {
  id: string;
  label: string;
  group: string;
  keywords: string;
  component: LucideIcon;
}

const groups: Array<{
  label: string;
  keywords: string;
  icons: Array<[string, string, LucideIcon]>;
}> = [
  {
    label: 'Điện lạnh và thông gió',
    keywords: 'máy lạnh điều hòa điều hoà air conditioner điện lạnh thông gió làm mát',
    icons: [
      ['air_vent', 'Máy lạnh', AirVent],
      ['snowflake', 'Làm lạnh', Snowflake],
      ['fan', 'Quạt', Fan],
      ['wind', 'Luồng gió', Wind],
      ['waves', 'Gió và nước', Waves],
      ['thermometer', 'Nhiệt kế', Thermometer],
      ['thermometer_snowflake', 'Đo nhiệt độ lạnh', ThermometerSnowflake],
      ['thermometer_sun', 'Đo nhiệt độ nóng', ThermometerSun],
      ['gauge', 'Đồng hồ áp suất', Gauge],
      ['settings', 'Điều chỉnh thiết bị', Settings],
      ['settings2', 'Cài đặt nhiệt độ', Settings2],
      ['sliders_horizontal', 'Điều chỉnh công suất', SlidersHorizontal],
      ['sliders_vertical', 'Điều chỉnh luồng gió', SlidersVertical],
      ['power', 'Bật tắt máy', Power],
      ['timer', 'Hẹn giờ', Timer],
      ['clock', 'Lịch bảo dưỡng', Clock],
      ['circle_gauge', 'Đồng hồ đo', CircleGauge],
      ['cloud_snow', 'Làm mát không khí', CloudSnow],
      ['cloud_sun', 'Nhiệt độ môi trường', CloudSun],
      ['sun', 'Sưởi ấm', Sun],
    ],
  },
  {
    label: 'Điện và chiếu sáng',
    keywords: 'điện dân dụng dây điện nguồn ổ cắm bóng đèn chiếu sáng',
    icons: [
      ['plug_zap', 'Sửa điện', PlugZap],
      ['plug', 'Phích cắm', Plug],
      ['plug2', 'Ổ cắm', Plug2],
      ['unplug', 'Ngắt điện', Unplug],
      ['zap', 'Dòng điện', Zap],
      ['zap_off', 'Mất điện', ZapOff],
      ['cable', 'Dây điện', Cable],
      ['cable_car', 'Cáp kéo', CableCar],
      ['lightbulb', 'Bóng đèn', Lightbulb],
      ['lightbulb_off', 'Đèn tắt', LightbulbOff],
      ['lamp', 'Đèn bàn', Lamp],
      ['lamp_desk', 'Đèn làm việc', LampDesk],
      ['lamp_ceiling', 'Đèn trần', LampCeiling],
      ['lamp_floor', 'Đèn đứng', LampFloor],
      ['lamp_wall_down', 'Đèn tường dưới', LampWallDown],
      ['lamp_wall_up', 'Đèn tường trên', LampWallUp],
      ['battery', 'Pin', Battery],
      ['battery_charging', 'Sạc pin', BatteryCharging],
      ['battery_full', 'Pin đầy', BatteryFull],
      ['utility_pole', 'Cột điện', UtilityPole],
    ],
  },
  {
    label: 'Nước và phòng tắm',
    keywords: 'nước đường ống ống nước bơm chống thấm phòng tắm vệ sinh',
    icons: [
      ['droplets', 'Giọt nước', Droplets],
      ['droplet', 'Nước', Droplet],
      ['droplet_off', 'Khóa nước', DropletOff],
      ['shower_head', 'Vòi sen', ShowerHead],
      ['bath', 'Bồn tắm', Bath],
      ['toilet', 'Bồn cầu', Toilet],
      ['wrench', 'Sửa đường ống', Wrench],
      ['pipette', 'Ống dẫn nhỏ', Pipette],
      ['glass_water', 'Nước sạch', GlassWater],
      ['waves_ladder', 'Hồ bơi', WavesLadder],
      ['life_buoy', 'Phao cứu sinh', LifeBuoy],
      ['container', 'Bể chứa', Container],
      ['cylinder', 'Ống trụ', Cylinder],
      ['circle_dashed', 'Gioăng ống', CircleDashed],
      ['circle_dot', 'Đầu nối ống', CircleDot],
      ['circle_off', 'Van khóa', CircleOff],
      ['refresh_cw', 'Tuần hoàn nước', RefreshCw],
      ['arrow_down_to_line', 'Thoát nước', ArrowDownToLine],
      ['arrow_up_from_line', 'Bơm nước', ArrowUpFromLine],
      ['filter', 'Lọc nước', Filter],
    ],
  },
  {
    label: 'Sửa chữa và xây dựng',
    keywords: 'sửa chữa lắp đặt bảo trì xây dựng dụng cụ thợ khoan mộc',
    icons: [
      ['hammer', 'Búa', Hammer],
      ['drill', 'Máy khoan', Drill],
      ['grip', 'Tay cầm dụng cụ', Grip],
      ['pickaxe', 'Cuốc', Pickaxe],
      ['axe', 'Rìu', Axe],
      ['ruler', 'Thước đo', Ruler],
      ['ruler_dimension_line', 'Đo kích thước', RulerDimensionLine],
      ['triangle_right', 'Thước vuông', TriangleRight],
      ['hard_hat', 'Mũ bảo hộ', HardHat],
      ['construction', 'Công trình', Construction],
      ['brick_wall', 'Tường gạch', BrickWall],
      ['paintbrush', 'Cọ sơn', Paintbrush],
      ['paint_roller', 'Con lăn sơn', PaintRoller],
      ['paint_bucket', 'Thùng sơn', PaintBucket],
      ['brush', 'Chổi quét sơn', Brush],
      ['anvil', 'Đe', Anvil],
      ['nut', 'Đai ốc', Nut],
      ['bolt', 'Bu lông', Bolt],
      ['pocket_knife', 'Dao đa năng', PocketKnife],
      ['tool_case', 'Hộp dụng cụ', ToolCase],
    ],
  },
  {
    label: 'Vệ sinh và giặt ủi',
    keywords: 'vệ sinh dọn dẹp lau nhà làm sạch giặt ủi tẩy rửa',
    icons: [
      ['sparkles', 'Làm sạch', Sparkles],
      ['spray_can', 'Bình xịt', SprayCan],
      ['bubbles', 'Bọt xà phòng', Bubbles],
      ['soap_dispenser_droplet', 'Bình xà phòng', SoapDispenserDroplet],
      ['washing_machine', 'Máy giặt', WashingMachine],
      ['shirt', 'Áo', Shirt],
      ['towel_rack', 'Giá treo khăn', TowelRack],
      ['hand', 'Vệ sinh thủ công', Hand],
      ['trash', 'Thùng rác', Trash],
      ['trash2', 'Thu gom rác', Trash2],
      ['recycle', 'Tái chế', Recycle],
      ['eraser', 'Tẩy vết bẩn', Eraser],
      ['paintbrush_vertical', 'Chổi cọ', PaintbrushVertical],
      ['brush_cleaning', 'Chổi vệ sinh', BrushCleaning],
      ['square_stack', 'Khăn xếp', SquareStack],
      ['hand_metal', 'Găng tay làm việc', HandMetal],
      ['scissors', 'Cắt sửa vải', Scissors],
      ['fold_horizontal', 'Gấp đồ', FoldHorizontal],
      ['fold_vertical', 'Gấp khăn', FoldVertical],
      ['rectangle_horizontal', 'Khăn lau', RectangleHorizontal],
    ],
  },
  {
    label: 'Nhà bếp và thực phẩm',
    keywords: 'bếp nấu ăn thực phẩm gia dụng nồi chảo rửa bát',
    icons: [
      ['cooking_pot', 'Nồi nấu', CookingPot],
      ['chef_hat', 'Đầu bếp', ChefHat],
      ['utensils', 'Dụng cụ ăn uống', Utensils],
      ['utensils_crossed', 'Chuẩn bị bữa ăn', UtensilsCrossed],
      ['microwave', 'Lò vi sóng', Microwave],
      ['refrigerator', 'Tủ lạnh', Refrigerator],
      ['heater', 'Bếp sưởi', Heater],
      ['coffee', 'Cà phê', Coffee],
      ['cup_soda', 'Đồ uống', CupSoda],
      ['wine', 'Ly rượu', Wine],
      ['bottle_wine', 'Chai rượu', BottleWine],
      ['soup', 'Món súp', Soup],
      ['sandwich', 'Bánh mì', Sandwich],
      ['egg_fried', 'Chảo trứng', EggFried],
      ['beef', 'Thịt', Beef],
      ['fish', 'Cá', Fish],
      ['salad', 'Rau trộn', Salad],
      ['apple', 'Trái cây', Apple],
      ['pizza', 'Bánh pizza', Pizza],
      ['cake', 'Bánh ngọt', Cake],
    ],
  },
  {
    label: 'Nhà cửa và nội thất',
    keywords: 'nhà cửa nội thất phòng ngủ phòng khách cửa sổ đồ gỗ',
    icons: [
      ['house', 'Nhà ở', House],
      ['house_plus', 'Cải tạo nhà', HousePlus],
      ['house_heart', 'Chăm sóc nhà', HouseHeart],
      ['house_plug', 'Thiết bị trong nhà', HousePlug],
      ['house_wifi', 'Nhà thông minh', HouseWifi],
      ['building', 'Tòa nhà', Building],
      ['building2', 'Chung cư', Building2],
      ['hotel', 'Phòng nghỉ', Hotel],
      ['sofa', 'Ghế sofa', Sofa],
      ['armchair', 'Ghế bành', Armchair],
      ['bed', 'Giường ngủ', Bed],
      ['bed_double', 'Giường đôi', BedDouble],
      ['bed_single', 'Giường đơn', BedSingle],
      ['door_open', 'Cửa mở', DoorOpen],
      ['door_closed', 'Cửa đóng', DoorClosed],
      ['panels_top_left', 'Cửa sổ', PanelsTopLeft],
      ['fence', 'Hàng rào', Fence],
      ['blinds', 'Rèm cửa', Blinds],
      ['wallpaper', 'Giấy dán tường', Wallpaper],
      ['grid2_x2', 'Danh mục chung', Grid2X2],
    ],
  },
  {
    label: 'Sân vườn và môi trường',
    keywords: 'sân vườn cây cỏ trồng cây tỉa cây môi trường ngoài trời',
    icons: [
      ['leaf', 'Lá cây', Leaf],
      ['leafy_green', 'Rau xanh', LeafyGreen],
      ['flower', 'Hoa', Flower],
      ['flower2', 'Chăm sóc hoa', Flower2],
      ['sprout', 'Cây giống', Sprout],
      ['tree_pine', 'Cây thông', TreePine],
      ['trees', 'Cây xanh', Trees],
      ['tree_deciduous', 'Cây bóng mát', TreeDeciduous],
      ['shrub', 'Bụi cây', Shrub],
      ['shovel', 'Xẻng', Shovel],
      ['snail', 'Ốc sên', Snail],
      ['bug', 'Côn trùng', Bug],
      ['bug_off', 'Diệt côn trùng', BugOff],
      ['rat', 'Diệt chuột', Rat],
      ['bird', 'Chim', Bird],
      ['cloud_rain', 'Tưới nước', CloudRain],
      ['sun_medium', 'Ánh nắng', SunMedium],
      ['sunrise', 'Sân vườn buổi sáng', Sunrise],
      ['tent', 'Lều', Tent],
      ['mountain', 'Cảnh quan', Mountain],
    ],
  },
  {
    label: 'Chăm sóc gia đình và thú cưng',
    keywords: 'chăm sóc trẻ em người già sức khỏe y tế thú cưng',
    icons: [
      ['baby', 'Trông trẻ', Baby],
      ['person_standing', 'Chăm sóc người lớn', PersonStanding],
      ['accessibility', 'Hỗ trợ đi lại', Accessibility],
      ['heart', 'Chăm sóc gia đình', Heart],
      ['heart_pulse', 'Theo dõi sức khỏe', HeartPulse],
      ['stethoscope', 'Khám tại nhà', Stethoscope],
      ['cross', 'Sơ cứu', Cross],
      ['bandage', 'Băng bó', Bandage],
      ['pill', 'Thuốc', Pill],
      ['syringe', 'Tiêm chăm sóc', Syringe],
      ['activity', 'Theo dõi vận động', Activity],
      ['hand_heart', 'Chăm sóc tận tình', HandHeart],
      ['hand_helping', 'Hỗ trợ gia đình', HandHelping],
      ['dog', 'Chó', Dog],
      ['cat', 'Mèo', Cat],
      ['paw_print', 'Chăm sóc thú cưng', PawPrint],
      ['rabbit', 'Thỏ', Rabbit],
      ['turtle', 'Rùa', Turtle],
      ['bone', 'Thức ăn thú cưng', Bone],
      ['footprints', 'Dắt thú cưng đi dạo', Footprints],
    ],
  },
  {
    label: 'Vận chuyển và xe cộ',
    keywords: 'vận chuyển chuyển nhà đóng gói xe cộ giao hàng sửa xe',
    icons: [
      ['truck', 'Xe vận chuyển', Truck],
      ['truck_electric', 'Xe điện vận chuyển', TruckElectric],
      ['car', 'Ô tô', Car],
      ['car_front', 'Sửa ô tô', CarFront],
      ['car_taxi_front', 'Xe đưa đón', CarTaxiFront],
      ['bike', 'Xe đạp', Bike],
      ['motorbike', 'Xe máy', Motorbike],
      ['bus', 'Xe khách', Bus],
      ['van', 'Xe tải nhỏ', Van],
      ['package', 'Đóng gói', Package],
      ['package_open', 'Mở thùng', PackageOpen],
      ['package_check', 'Kiểm tra kiện hàng', PackageCheck],
      ['package_plus', 'Thêm kiện hàng', PackagePlus],
      ['boxes', 'Thùng hàng', Boxes],
      ['box', 'Hộp', Box],
      ['archive', 'Lưu kho', Archive],
      ['warehouse', 'Kho hàng', Warehouse],
      ['forklift', 'Xe nâng', Forklift],
      ['luggage', 'Hành lý', Luggage],
      ['baggage_claim', 'Vận chuyển hành lý', BaggageClaim],
    ],
  },
  {
    label: 'An ninh và an toàn',
    keywords: 'an ninh bảo vệ khóa cửa camera phòng cháy an toàn',
    icons: [
      ['shield', 'Bảo vệ', Shield],
      ['shield_check', 'An toàn đã kiểm tra', ShieldCheck],
      ['shield_alert', 'Cảnh báo an ninh', ShieldAlert],
      ['shield_plus', 'Tăng cường bảo vệ', ShieldPlus],
      ['shield_half', 'Chắn bảo vệ', ShieldHalf],
      ['lock', 'Khóa cửa', Lock],
      ['lock_open', 'Mở khóa', LockOpen],
      ['key', 'Chìa khóa', Key],
      ['key_round', 'Chìa khóa tròn', KeyRound],
      ['key_square', 'Chìa khóa vuông', KeySquare],
      ['cctv', 'Camera giám sát', Cctv],
      ['camera', 'Camera', Camera],
      ['video', 'Ghi hình', Video],
      ['bell_electric', 'Chuông cửa', BellElectric],
      ['bell_ring', 'Chuông báo', BellRing],
      ['siren', 'Còi báo động', Siren],
      ['fire_extinguisher', 'Bình chữa cháy', FireExtinguisher],
      ['flame', 'Phòng cháy', Flame],
      ['alarm_smoke', 'Báo khói', AlarmSmoke],
      ['fingerprint', 'Khóa vân tay', Fingerprint],
    ],
  },
  {
    label: 'Điện tử và tiện ích gia đình',
    keywords: 'điện tử thiết bị máy tính mạng internet ti vi âm thanh gia đình',
    icons: [
      ['tv', 'Ti vi', Tv],
      ['tv_minimal', 'Màn hình ti vi', TvMinimal],
      ['monitor', 'Màn hình máy tính', Monitor],
      ['monitor_cog', 'Sửa màn hình', MonitorCog],
      ['laptop', 'Máy tính xách tay', Laptop],
      ['computer', 'Máy tính bàn', Computer],
      ['smartphone', 'Điện thoại', Smartphone],
      ['tablet', 'Máy tính bảng', Tablet],
      ['printer', 'Máy in', Printer],
      ['router', 'Bộ phát mạng', Router],
      ['wifi', 'Mạng không dây', Wifi],
      ['ethernet_port', 'Cổng mạng', EthernetPort],
      ['speaker', 'Loa', Speaker],
      ['headphones', 'Tai nghe', Headphones],
      ['radio', 'Radio', Radio],
      ['gamepad2', 'Máy chơi game', Gamepad2],
      ['projector', 'Máy chiếu', Projector],
      ['usb', 'Cổng USB', Usb],
      ['circuit_board', 'Bo mạch', CircuitBoard],
      ['cpu', 'Vi xử lý', Cpu],
    ],
  },
];

export const CATEGORY_ICON_GROUPS = groups.map((group) => group.label);
export const CATEGORY_ICONS: CategoryIconOption[] = groups.flatMap((group) =>
  group.icons.map(([id, label, component]) => ({
    id: `lucide:${id}`, label, component, group: group.label, keywords: group.keywords,
  })),
);

export const normalizeIconSearch = (value: string) => value
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .replace(/[đĐ]/g, 'd')
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, ' ')
  .trim();

const searchableIcons = CATEGORY_ICONS.map((option) => ({
  option,
  search: normalizeIconSearch(
    `${option.label} ${option.id} ${option.group} ${option.keywords}`,
  ),
}));

export const searchCategoryIcons = (query: string, group = '') => {
  const words = normalizeIconSearch(query).split(' ').filter(Boolean);
  return searchableIcons
    .filter(({ option, search }) => (!group || option.group === group)
      && words.every((word) => search.includes(word)))
    .map(({ option }) => option);
};

const legacyAliases: Record<string, string> = {
  category: 'grid2_x2', apps: 'grid2_x2',
  electrical: 'plug_zap', electrical_services: 'plug_zap', electricity: 'plug_zap',
  bolt: 'plug_zap', dien_dan_dung: 'plug_zap',
  air_conditioning: 'snowflake', ac_unit: 'snowflake', dien_lanh: 'snowflake',
  plumbing: 'wrench', water: 'droplets', water_drop: 'droplets', nuoc_va_duong_ong: 'wrench',
  cleaning: 'sparkles', cleaning_services: 'sparkles', spray_cleaning: 'spray_can', ve_sinh_nha_cua: 'sparkles',
  appliance_repair: 'drill', home_repair_service: 'drill', home_repair: 'hammer', sua_chua_gia_dung: 'drill',
  handyman: 'hammer', construction: 'hammer', painting: 'paintbrush', format_paint: 'paintbrush',
  laundry: 'shirt', local_laundry_service: 'shirt', cooking: 'cooking_pot', restaurant: 'cooking_pot',
  gardening: 'leaf', yard: 'leaf', pest_control: 'bug', car_repair: 'car',
  childcare: 'baby', child_care: 'baby', pet_care: 'paw_print', pets: 'paw_print',
  security: 'shield_check', shield: 'shield_check', home: 'house',
};

const iconsById = new Map(CATEGORY_ICONS.map((option) => [option.id, option]));

export const resolveCategoryIcon = (icon?: string | null, name?: string) => {
  for (const value of [icon, name]) {
    const exact = iconsById.get(value || '');
    if (exact) return exact;
    const key = normalizeIconSearch(value || '').replace(/ /g, '_');
    const option = iconsById.get(`lucide:${legacyAliases[key] || key}`);
    if (option) return option;
  }
  return iconsById.get('lucide:grid2_x2')!;
};

export const DEFAULT_CATEGORY_ICON_COLOR = '#3525cd';
export const CATEGORY_ICON_COLORS = [
  { value: '#3525cd', label: 'Chàm' },
  { value: '#7c3aed', label: 'Tím' },
  { value: '#2563eb', label: 'Xanh dương' },
  { value: '#0891b2', label: 'Xanh ngọc' },
  { value: '#059669', label: 'Xanh lá' },
  { value: '#d97706', label: 'Cam' },
  { value: '#dc2626', label: 'Đỏ' },
  { value: '#db2777', label: 'Hồng' },
];

export const getAvailableCategoryIconColor = (usedColors: string[]) => {
  const used = new Set(usedColors.map((color) => color.toLowerCase()));
  const preset = CATEGORY_ICON_COLORS.find((color) => !used.has(color.value));
  if (preset) return preset.value;
  let value = 0x3525cd;
  while (used.has(`#${value.toString(16).padStart(6, '0')}`)) {
    value = (value + 0x9e3779) % 0x1000000;
  }
  return `#${value.toString(16).padStart(6, '0')}`;
};

export const isCategoryIconColor = (color?: string | null): color is string =>
  typeof color === 'string' && /^#[0-9a-f]{6}$/i.test(color);

