name: handigo_app
description: "Ứng dụng di động Handigo"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^17.0.0
  dio: ^5.9.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  speech_to_text: ^7.0.0
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/handigo-logo.png
    - assets/payments/payos-logo.png
      - assets/icons/account/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-variable.ttf
    - family: Hanken Grotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-variable.ttf
