/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary": "#ffffff",
              "surface-container-highest": "#dae2fd",
              "surface-container-lowest": "#ffffff",
              "on-surface": "#131b2e",
              "inverse-primary": "#c3c0ff",
              "on-secondary": "#ffffff",
              "secondary-container": "#57dffe",
              "on-secondary-fixed": "#001f26",
              "on-surface-variant": "#464555",
              "inverse-on-surface": "#eef0ff",
              "on-primary": "#ffffff",
              "background": "#faf8ff",
              "tertiary": "#7e3000",
              "primary-fixed": "#e2dfff",
              "secondary": "#00687a",
              "tertiary-fixed-dim": "#ffb695",
              "secondary-fixed-dim": "#4cd7f6",
              "primary": "#3525cd",
              "on-secondary-container": "#006172",
              "surface-dim": "#d2d9f4",
              "secondary-fixed": "#acedff",
              "primary-container": "#4f46e5",
              "outline-variant": "#c7c4d8",
              "on-primary-container": "#dad7ff",
              "on-error": "#ffffff",
              "outline": "#777587",
              "error-container": "#ffdad6",
              "tertiary-fixed": "#ffdbcc",
              "on-background": "#131b2e",
              "on-primary-fixed-variant": "#3323cc",
              "surface-container": "#eaedff",
              "on-tertiary-fixed-variant": "#7b2f00",
              "surface-bright": "#faf8ff",
              "surface-tint": "#4d44e3",
              "surface": "#faf8ff",
              "error": "#ba1a1a",
              "on-error-container": "#93000a",
              "tertiary-container": "#a44100",
              "on-secondary-fixed-variant": "#004e5c",
              "surface-container-low": "#f2f3ff",
              "surface-variant": "#dae2fd",
              "surface-container-high": "#e2e7ff",
              "primary-fixed-dim": "#c3c0ff",
              "inverse-surface": "#283044",
              "on-tertiary-container": "#ffd2be",
              "on-primary-fixed": "#0f0069",
              "on-tertiary-fixed": "#351000"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "2xl": "1rem",
              "3xl": "1.5rem",
              "full": "9999px"
      },
      "spacing": {
              "md": "24px",
              "lg": "48px",
              "base": "8px",
              "sm": "12px",
              "xs": "4px",
              "xl": "80px",
              "container-max": "1280px",
              "gutter": "24px"
      },
      "fontFamily": {
              "body-lg": ["Inter"],
              "label-sm": ["Inter"],
              "headline-xl": ["Hanken Grotesk"],
              "label-md": ["Inter"],
              "headline-md": ["Hanken Grotesk"],
              "body-md": ["Inter"],
              "headline-lg-mobile": ["Hanken Grotesk"],
              "headline-lg": ["Hanken Grotesk"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
              "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
